[project]
name = "zipinspect"
author = "Cynthia"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "click>=8.3.1",
    "httpx[http2]>=0.28.1",
    "tabulate>=0.9.0",
    "tqdm>=4.67.2"
]
