[project]
name = "zipinspect"
author = "Cynthia"
description = "Small utility to inspect/extract Zip files over HTTP"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "aioconsole>=0.8.2",
    "tabulate>=0.9.0",
    "progress>=1.6.1",
    "httpx[http2]>=0.28.1",
]
